# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: D

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dlang-community/setup-dlang@4c99aa991ce7d19dd3064de0a4f2f6b2f152e2d7

    - name: Build gifPauser
      run: |
        dub upgrade && dub run raylib-d:install
        dub build --compiler=dmd --build=release

    - name: Upload gifPauser
      uses: actions/upload-artifact@v4
      with:
        name: gifPauser
        path: build/
